import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "introduction",
    "getting-started",
    {
      type: "category",
      label: "React",
      items: [
        "react/overview",
        {
          type: "category",
          label: "Components",
          items: ["react/components/wallet"],
        }, {
          type: "category",
          label: "Hooks",
          items: ["react/hooks/use-broadcast", "react/hooks/use-wallet"],
        }
      ],
    },
    {
      type: "category",
      label: "API Reference",
      items: [{
          type: "autogenerated",
          dirName: "api",
      }],
    }
  ],
};

export default sidebars;
