import type { Metadata } from "next";
import localFont from "next/font/local";
import "@microcosm/react/tailwind-styles.css";
import { MicrocosmProvider } from "@microcosm/react/contexts";
// import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MicrocosmProvider
          config={{
            chainId: "kaiyo-1",
            rpcUrl: "https://rpc-kujira.mintthemoon.xyz",
            // featuredTokens: [
            //   "ukuji",
            //   "factory/kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7/uusk",
            //   "factory/kujira12cjjeytrqcj25uv349thltcygnp9k0kukpct0e/uwink",
            // ],
          }}>
            {children}
          </MicrocosmProvider>
      </body>
    </html>
  );
}
